[2022-02-28 08:57:07,638] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.upload_file_to_S3 scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 08:57:07,653] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.upload_file_to_S3 scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 08:57:07,654] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 08:57:07,655] {taskinstance.py:1244} INFO - Starting attempt 16 of 16
[2022-02-28 08:57:07,656] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 08:57:07,676] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): upload_file_to_S3> on 2022-02-25 00:00:00+00:00
[2022-02-28 08:57:07,687] {standard_task_runner.py:52} INFO - Started process 20341 to run task
[2022-02-28 08:57:07,693] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_s3_connection', 'upload_file_to_S3', 'scheduled__2022-02-25T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpkfkqv1n3', '--error-file', '/tmp/tmpdwz0m7g4']
[2022-02-28 08:57:07,695] {standard_task_runner.py:77} INFO - Job 79: Subtask upload_file_to_S3
[2022-02-28 08:57:07,764] {logging_mixin.py:109} INFO - Running <TaskInstance: test_s3_connection.upload_file_to_S3 scheduled__2022-02-25T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-02-28 08:57:07,831] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_s3_connection
AIRFLOW_CTX_TASK_ID=upload_file_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T00:00:00+00:00
[2022-02-28 08:57:07,845] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-02-28 08:57:09,843] {python.py:175} INFO - Done. Returned value was: None
[2022-02-28 08:57:09,862] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=test_s3_connection, task_id=upload_file_to_S3, execution_date=20220225T000000, start_date=20220228T085707, end_date=20220228T085709
[2022-02-28 08:57:09,933] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 08:57:09,997] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
