[2022-03-14 09:42:09,447] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.create_bucket scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-14 09:42:09,478] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.create_bucket scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-14 09:42:09,480] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 09:42:09,481] {taskinstance.py:1244} INFO - Starting attempt 10 of 10
[2022-03-14 09:42:09,483] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 09:42:09,519] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): create_bucket> on 2022-03-13 00:00:00+00:00
[2022-03-14 09:42:09,536] {standard_task_runner.py:52} INFO - Started process 8556 to run task
[2022-03-14 09:42:09,552] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'glue_poc', 'create_bucket', 'scheduled__2022-03-13T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/glue_poc.py', '--cfg-path', '/tmp/tmpjoly6epx', '--error-file', '/tmp/tmpwb2n2gqy']
[2022-03-14 09:42:09,555] {standard_task_runner.py:77} INFO - Job 123: Subtask create_bucket
[2022-03-14 09:42:09,698] {logging_mixin.py:109} INFO - Running <TaskInstance: glue_poc.create_bucket scheduled__2022-03-13T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-03-14 09:42:09,844] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=glue_poc
AIRFLOW_CTX_TASK_ID=create_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-13T00:00:00+00:00
[2022-03-14 09:42:09,878] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-14 09:42:11,865] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 09:42:11,922] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=glue_poc, task_id=create_bucket, execution_date=20220313T000000, start_date=20220314T094209, end_date=20220314T094211
[2022-03-14 09:42:12,004] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 09:42:12,079] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
