[2022-02-28 10:25:24,074] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.read_file_from_s3 scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 10:25:24,092] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.read_file_from_s3 scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 10:25:24,094] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 10:25:24,095] {taskinstance.py:1244} INFO - Starting attempt 24 of 24
[2022-02-28 10:25:24,096] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 10:25:24,168] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): read_file_from_s3> on 2022-02-25 00:00:00+00:00
[2022-02-28 10:25:24,181] {standard_task_runner.py:52} INFO - Started process 25936 to run task
[2022-02-28 10:25:24,194] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_s3_connection', 'read_file_from_s3', 'scheduled__2022-02-25T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpzv28rrc_', '--error-file', '/tmp/tmp_a3p1jfp']
[2022-02-28 10:25:24,199] {standard_task_runner.py:77} INFO - Job 101: Subtask read_file_from_s3
[2022-02-28 10:25:24,301] {logging_mixin.py:109} INFO - Running <TaskInstance: test_s3_connection.read_file_from_s3 scheduled__2022-02-25T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-02-28 10:25:24,405] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_s3_connection
AIRFLOW_CTX_TASK_ID=read_file_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T00:00:00+00:00
[2022-02-28 10:25:24,430] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-02-28 10:25:26,735] {logging_mixin.py:109} INFO - ['id', 'name', 'department', 'raise']
[2022-02-28 10:25:26,739] {logging_mixin.py:109} INFO - [['1', 'Jaskirat', 'MLOps', '15'], ['2', 'Jasmine', 'HybridApps', '20'], ['3', 'Nipun', 'Law', '10'], ['4', 'Dantin', 'FullStack', '14'], ['5', 'Renu', 'Marketing', '12']]
[2022-02-28 10:25:26,743] {python.py:175} INFO - Done. Returned value was: None
[2022-02-28 10:25:26,929] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=test_s3_connection, task_id=read_file_from_s3, execution_date=20220225T000000, start_date=20220228T102524, end_date=20220228T102526
[2022-02-28 10:25:27,040] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 10:25:27,207] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
